name: KUBESEC
channels:
  - conda-forge     # conda‑forge first gives you most of the Python ecosystem
  - defaults
channel_priority: strict

dependencies:
  # Core runtime
  - python =3.11
  - pip             # needed for the pip: section below

  # Heavy, compiled, or conda‑forge‑only libs
  - numpy
  - pandas
  - ruamel.yaml
  - sarif-om
  - jschema-to-python

  # Unit‑test + tooling
  - pytest
  - hypothesis
  - bandit

  # Anything else comes from pip ↓
  - pip:
      - -r requirements.txt
