name: KUBESEC
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11           
  - pip                  
  - numpy                
  - pandas
  - ruamel.yaml
  - sarif-om
  - jschema-to-python
  - pytest
  - hypothesis
  - bandit
  - pip:                
      - -r requirements.txt
