name: Fuzz Testing

on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'


jobs:
  test:
    runs-on: ubuntu-latest

    defaults:            # 👈 keeps Conda activation alive
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Remove old env
      run: conda env remove -n KUBESEC || true

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: KUBESEC
        python-version: 3.11
        auto-update-conda: true

    - name: Verify environment
      run: conda list

    - name: Run fuzz tests
      run: python fuzz.py
