name: Fuzz Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11  # Match the Python version in environment.yml
        environment-file: environment.yml
        activate-environment: KUBESEC

    - name: Verify environment
      run: conda list

    - name: Run fuzz tests
      run: python fuzz.py